name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12, 14]
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn start
          wait-on: 'http://localhost:8080'
          wait-on-timeout: 110
      - name: Upload artifacts  # Find artifacts under actions/jobs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: snapshots
          path: ./cypress/
