# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish to NPM

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - name: Test
        run: yarn test:unit
      - name: Build
        run: yarn build
      - uses: actions/upload-artifact@v1
        with:
          name: build_123
          path: dist

  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: build_123
      - shell: bash
        run: |
          npm publish --dry-run
      # - name: Publish
      #   uses: mikeal/merge-release@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}